#!/usr/bin/env python3
"""Materialize work packets from baseline/exclusion ledgers.

Usage:
  Phase 2 classification:
    python materialize-work-packets.py --mode classify --exclusions <ledger.md> --phase 2 --output <out.md>

  Phase 3 repair:
    python materialize-work-packets.py --mode repair --baseline <ledger.md> --phase 3 --output <out.md>

  Phase 11-13 repair:
    python materialize-work-packets.py --mode repair --baseline <ledger.md> --exclusions <ledger.md> --phase 11 --output <out.md>
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_utf8(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def read_lines(path: Path) -> list[str]:
    return read_utf8(path).splitlines()


def parse_table(lines: list[str], header: str) -> list[dict[str, str]]:
    """Parse a markdown table with the given header prefix."""
    results = []
    in_table = False
    col_names = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("|") and header in stripped:
            col_names = [c.strip() for c in stripped.strip("|").split("|")]
            col_names = [c for c in col_names if c]
            in_table = True
            continue
        if in_table:
            if not stripped.startswith("|") or "---" in stripped:
                continue
            if stripped.startswith("|"):
                cells = [c.strip() for c in stripped.strip("|").split("|")]
                cells = [c for c in cells if c]
                if len(cells) == len(col_names):
                    row = dict(zip(col_names, cells))
                    row_id = row.get("ID", "")
                    if row_id:
                        results.append(row)
                else:
                    # table ended
                    in_table = False
    return results


def parse_ledger(path: Path) -> list[dict[str, str]]:
    lines = read_lines(path)
    return parse_table(lines, "ID | Platform | Command")


def parse_exclusions(path: Path) -> list[dict[str, str]]:
    lines = read_lines(path)
    return parse_table(lines, "ID | file | line")


def parse_classify_cards(path: Path) -> list[dict[str, str]]:
    lines = read_lines(path)
    return parse_table(lines, "ID | file | line")


def stable_sort_key(row: dict[str, str]) -> tuple:
    return (
        row.get("owner phase", row.get("Owner Phase", "")),
        row.get("file", ""),
        row.get("line", ""),
        row.get("symbol/test", ""),
        row.get("ID", ""),
    )


def fingerprint(row: dict[str, str]) -> str:
    """Normalized causal fingerprint — removes paths and line numbers."""
    error = row.get("First Causal Error", row.get("first causal error", ""))
    error = re.sub(r"\S+/\S+", "<PATH>", error)
    error = re.sub(r":\d+:\d+", ":<LN>", error)
    return error


def classify_mode(args):
    if not args.exclusions:
        sys.exit("classify mode requires --exclusions")
    excl = parse_exclusions(args.exclusions)
    print(f"Parsed {len(excl)} exclusion rows", file=sys.stderr)

    excl.sort(key=stable_sort_key)

    input_sha = sha256_file(args.exclusions)

    lines = [
        f"# Phase {args.phase} Classification Cards",
        f"# Input: exclusions ledger SHA-256: {input_sha}",
        f"# Generated by materialize-work-packets.py --mode classify --phase {args.phase}",
        "",
        "## Cards",
        "",
    ]

    for i, row in enumerate(excl):
        wid = row.get("ID", f"WX-UNKNOWN-{i}")
        card_id = f"P{args.phase}-C-{wid}"
        fp = fingerprint(row)
        lines.append(f"### {card_id}: classify {wid}")
        lines.append("")
        lines.append("- Ledger ID: " + wid)
        lines.append("- File: " + row.get("file", ""))
        lines.append("- Line: " + row.get("line", ""))
        lines.append("- Symbol: " + row.get("symbol/test", ""))
        lines.append("- Cfg: " + row.get("cfg expression", ""))
        lines.append("- Fingerprint: " + fp)
        lines.append("- Status: NOT_STARTED")
        lines.append("")

    output = "\n".join(lines)
    output_sha = hashlib.sha256(output.encode()).hexdigest()
    print(f"Output SHA-256: {output_sha}", file=sys.stderr)

    if args.check:
        existing = Path(args.output)
        if existing.exists():
            existing_sha = sha256_file(existing)
            if existing_sha != output_sha:
                sys.exit(f"CHECK FAILED: {args.output} has been tampered with (SHA mismatch)")
        else:
            sys.exit(f"CHECK FAILED: {args.output} does not exist")
    else:
        Path(args.output).write_text(output, newline='\n')
        print(f"Wrote {args.output}", file=sys.stderr)


def repair_mode(args):
    if not args.baseline:
        sys.exit("repair mode requires --baseline")
    ledger = parse_ledger(args.baseline)
    print(f"Parsed {len(ledger)} ledger rows", file=sys.stderr)

    excl = []
    if args.exclusions:
        excl = parse_exclusions(args.exclusions)
        print(f"Parsed {len(excl)} exclusion rows", file=sys.stderr)

    rows = ledger + excl
    if not rows:
        sys.exit("No rows to materialize")

    # Group by normalized fingerprint for foundation groups
    groups: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        fp = fingerprint(row)
        func = (row.get("symbol/test", row.get("symbol", "")))
        prod_sym = (row.get("production symbol", "") or func)
        group_key = f"{fp}||{prod_sym}"
        groups.setdefault(group_key, []).append(row)

    input_sha_baseline = sha256_file(args.baseline)
    lines = [
        f"# Phase {args.phase} Repair Cards",
        f"# Input: baseline ledger SHA-256: {input_sha_baseline}",
    ]
    if args.exclusions:
        input_sha_excl = sha256_file(args.exclusions)
        lines.append(f"# Input: exclusions ledger SHA-256: {input_sha_excl}")
    lines.append(f"# Generated by materialize-work-packets.py --mode repair --phase {args.phase}")
    lines.append("")

    card_idx = 0
    for gk, gmembers in sorted(groups.items()):
        sorted_members = sorted(gmembers, key=stable_sort_key)
        if len(sorted_members) == 1:
            row = sorted_members[0]
            card_idx += 1
            lid = row.get("ID", f"ROW-{card_idx:03d}")
            card_id = f"P{args.phase}-R-{lid}"
            lines.append(f"### {card_id}: repair {lid}")
            lines.append("")
            lines.append("- Ledger ID: " + lid)
            lines.append("- Platform: " + row.get("Platform", ""))
            lines.append("- Package: " + row.get("Package/Target", ""))
            lines.append("- Failure class: " + row.get("Failure Class", ""))
            lines.append("- First causal error: " + row.get("First Causal Error", ""))
            lines.append("- Fingerprint: " + fingerprint(row))
            lines.append("- Status: NOT_STARTED")
            lines.append("")
        else:
            card_idx += 1
            lids = [r["ID"] for r in sorted_members]
            card_id = f"P{args.phase}-R-GROUP-{card_idx:03d}"
            lines.append(f"### {card_id}: foundation group ({len(lids)} rows)")
            lines.append("")
            for r in sorted_members:
                lines.append("- " + r.get("ID", "") + ": " + r.get("First Causal Error", ""))
            lines.append("- Fingerprint: " + fp)
            lines.append("- Status: NOT_STARTED")
            lines.append("")

    output = "\n".join(lines)
    output_sha = hashlib.sha256(output.encode()).hexdigest()
    print(f"Output SHA-256: {output_sha}", file=sys.stderr)

    if args.check:
        existing = Path(args.output)
        if existing.exists():
            existing_sha = sha256_file(existing)
            if existing_sha != output_sha:
                sys.exit(f"CHECK FAILED: {args.output} has been tampered with (SHA mismatch)")
        else:
            sys.exit(f"CHECK FAILED: {args.output} does not exist")
    else:
        Path(args.output).write_text(output, newline='\n')
        print(f"Wrote {args.output}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="Materialize work packets")
    parser.add_argument("--mode", choices=["classify", "repair"], required=True)
    parser.add_argument("--baseline", type=Path, help="Baseline failure ledger path")
    parser.add_argument("--exclusions", type=Path, help="Windows exclusion ledger path")
    parser.add_argument("--phase", type=int, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true", help="Verify existing output is unmodified")
    args = parser.parse_args()

    if args.mode == "classify":
        classify_mode(args)
    else:
        repair_mode(args)


if __name__ == "__main__":
    main()
